# Dot-sourced by re.ps1. Uses shared REToolkit variables from the entrypoint.

function Show-Usage {
    Write-Host "RE Toolkit - RE Pipeline Runner" -ForegroundColor Magenta
    Write-Host ""
    Write-Host "Pipeline commands:"
    Write-Host "  .\re.ps1 doctor"
    Write-Host "  .\re.ps1 init       <GameName>"
    Write-Host "  .\re.ps1 add        <GameName> <apk-or-xapk-or-aab-or-zip>"
    Write-Host "  .\re.ps1 scan       <GameName> <ExtractedPath>"
    Write-Host "  .\re.ps1 dump       <GameName>"
    Write-Host "  .\re.ps1 import     <GameName>                         # import only; no Ghidra analysis"
    Write-Host "  .\re.ps1 analyze    <GameName>                         # manual/optional; not used by flow"
    Write-Host "  .\re.ps1 symbols    <GameName>                         # manual/optional; not used by flow"
    Write-Host "  .\re.ps1 flow       <GameName> <apk-or-ExtractedPath>  # dump/import/open PyGhidra; no headless analyze"
    Write-Host "  .\re.ps1 open       <GameName>                         # open imported project in PyGhidra GUI"
    Write-Host "  .\re.ps1 path       <GameName>                         # print Ghidra project folder/link for GUI open"
    Write-Host "  .\re.ps1 status     <GameName>"
    Write-Host "  .\re.ps1 candidates <GameName>"
    Write-Host "  .\re.ps1 context    <GameName>"
    Write-Host "  .\re.ps1 notes      <GameName>"
    Write-Host ""
    Write-Host "Tool wrappers:"
    Write-Host "  .\re.ps1 ghidra-gui [GameName]"
    Write-Host "  .\re.ps1 pyghidra-gui [GameName]"
    Write-Host "  .\re.ps1 il2cppdumper <args...>"
    Write-Host "  .\re.ps1 mcp                         # MCP bridge for AI clients"
    Write-Host ""
    Write-Host "MCP query workflow:"
    Write-Host "  1. Open project/program in Ghidra or PyGhidra GUI."
    Write-Host "  2. Enable: File > Configure > Configure All Plugins > GhidraMCP"
    Write-Host "  3. Start:  Tools > GhidraMCP > Start MCP Server"
    Write-Host "  4. Start the client bridge: .\re.ps1 mcp"
}
